// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HashRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashRequest) Reset()         { *m = HashRequest{} }
func (m *HashRequest) String() string { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()    {}
func (*HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashRequest.Unmarshal(m, b)
}
func (m *HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashRequest.Marshal(b, m, deterministic)
}
func (m *HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRequest.Merge(m, src)
}
func (m *HashRequest) XXX_Size() int {
	return xxx_messageInfo_HashRequest.Size(m)
}
func (m *HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashRequest proto.InternalMessageInfo

func (m *HashRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type HashReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PasswordHash         string   `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashReply) Reset()         { *m = HashReply{} }
func (m *HashReply) String() string { return proto.CompactTextString(m) }
func (*HashReply) ProtoMessage()    {}
func (*HashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *HashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashReply.Unmarshal(m, b)
}
func (m *HashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashReply.Marshal(b, m, deterministic)
}
func (m *HashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashReply.Merge(m, src)
}
func (m *HashReply) XXX_Size() int {
	return xxx_messageInfo_HashReply.Size(m)
}
func (m *HashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HashReply.DiscardUnknown(m)
}

var xxx_messageInfo_HashReply proto.InternalMessageInfo

func (m *HashReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HashReply) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

type AuthenticationRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationRequest) Reset()         { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()    {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *AuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationRequest.Unmarshal(m, b)
}
func (m *AuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationRequest.Merge(m, src)
}
func (m *AuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticationRequest.Size(m)
}
func (m *AuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationRequest proto.InternalMessageInfo

func (m *AuthenticationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthenticationReply struct {
	Authenticated        bool         `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Claims               *TokenClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AuthenticationReply) Reset()         { *m = AuthenticationReply{} }
func (m *AuthenticationReply) String() string { return proto.CompactTextString(m) }
func (*AuthenticationReply) ProtoMessage()    {}
func (*AuthenticationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthenticationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationReply.Unmarshal(m, b)
}
func (m *AuthenticationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationReply.Marshal(b, m, deterministic)
}
func (m *AuthenticationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationReply.Merge(m, src)
}
func (m *AuthenticationReply) XXX_Size() int {
	return xxx_messageInfo_AuthenticationReply.Size(m)
}
func (m *AuthenticationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationReply.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationReply proto.InternalMessageInfo

func (m *AuthenticationReply) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticationReply) GetClaims() *TokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type AuthTokenRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenRequest) Reset()         { *m = AuthTokenRequest{} }
func (m *AuthTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AuthTokenRequest) ProtoMessage()    {}
func (*AuthTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AuthTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenRequest.Unmarshal(m, b)
}
func (m *AuthTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenRequest.Marshal(b, m, deterministic)
}
func (m *AuthTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenRequest.Merge(m, src)
}
func (m *AuthTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AuthTokenRequest.Size(m)
}
func (m *AuthTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenRequest proto.InternalMessageInfo

func (m *AuthTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AuthTokenReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenReply) Reset()         { *m = AuthTokenReply{} }
func (m *AuthTokenReply) String() string { return proto.CompactTextString(m) }
func (*AuthTokenReply) ProtoMessage()    {}
func (*AuthTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *AuthTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenReply.Unmarshal(m, b)
}
func (m *AuthTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenReply.Marshal(b, m, deterministic)
}
func (m *AuthTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenReply.Merge(m, src)
}
func (m *AuthTokenReply) XXX_Size() int {
	return xxx_messageInfo_AuthTokenReply.Size(m)
}
func (m *AuthTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenReply proto.InternalMessageInfo

func (m *AuthTokenReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthTokenReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TokenClaims struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Exp                  int64    `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenClaims) Reset()         { *m = TokenClaims{} }
func (m *TokenClaims) String() string { return proto.CompactTextString(m) }
func (*TokenClaims) ProtoMessage()    {}
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *TokenClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenClaims.Unmarshal(m, b)
}
func (m *TokenClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenClaims.Marshal(b, m, deterministic)
}
func (m *TokenClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenClaims.Merge(m, src)
}
func (m *TokenClaims) XXX_Size() int {
	return xxx_messageInfo_TokenClaims.Size(m)
}
func (m *TokenClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenClaims.DiscardUnknown(m)
}

var xxx_messageInfo_TokenClaims proto.InternalMessageInfo

func (m *TokenClaims) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenClaims) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func init() {
	proto.RegisterType((*HashRequest)(nil), "auth_service.HashRequest")
	proto.RegisterType((*HashReply)(nil), "auth_service.HashReply")
	proto.RegisterType((*AuthenticationRequest)(nil), "auth_service.AuthenticationRequest")
	proto.RegisterType((*AuthenticationReply)(nil), "auth_service.AuthenticationReply")
	proto.RegisterType((*AuthTokenRequest)(nil), "auth_service.AuthTokenRequest")
	proto.RegisterType((*AuthTokenReply)(nil), "auth_service.AuthTokenReply")
	proto.RegisterType((*TokenClaims)(nil), "auth_service.TokenClaims")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x2d, 0xd6, 0x76, 0x92, 0x4a, 0x59, 0x15, 0x6b, 0x10, 0xd1, 0xad, 0x07, 0x3d, 0x58,
	0xb0, 0x1e, 0xbd, 0x28, 0x0a, 0x4a, 0x0f, 0x22, 0xd1, 0x83, 0xb7, 0xb2, 0xc6, 0xc1, 0x04, 0xf3,
	0x65, 0x76, 0xa3, 0xf6, 0xc7, 0x0b, 0xb2, 0x9b, 0x0f, 0x37, 0x35, 0x8a, 0xb7, 0x9d, 0x9d, 0xb7,
	0xef, 0xbd, 0x79, 0xb3, 0x00, 0x2c, 0x13, 0xde, 0x38, 0x49, 0x63, 0x11, 0x13, 0x4b, 0x9e, 0x67,
	0x1c, 0xd3, 0x37, 0xdf, 0x45, 0x7a, 0x08, 0xe6, 0x35, 0xe3, 0x9e, 0x83, 0xaf, 0x19, 0x72, 0x41,
	0x6c, 0xe8, 0x26, 0x8c, 0xf3, 0xf7, 0x38, 0x7d, 0x1a, 0x1a, 0xbb, 0xc6, 0x41, 0xcf, 0xa9, 0x6a,
	0x3a, 0x85, 0x5e, 0x0e, 0x4d, 0x82, 0x39, 0x19, 0xc2, 0x4a, 0x88, 0x9c, 0xb3, 0x67, 0x2c, 0x70,
	0x65, 0x49, 0x46, 0xd0, 0x2f, 0x9f, 0xcc, 0x3c, 0xc6, 0xbd, 0x61, 0x4b, 0xf5, 0xad, 0xf2, 0x52,
	0x72, 0xd0, 0x23, 0xd8, 0x38, 0xcf, 0x84, 0x87, 0x91, 0xf0, 0x5d, 0x26, 0xfc, 0x38, 0x2a, 0x0d,
	0xac, 0xc3, 0xb2, 0x88, 0x5f, 0x30, 0x2a, 0x58, 0xf3, 0x82, 0x46, 0xb0, 0xb6, 0x08, 0x97, 0x26,
	0xf6, 0xa1, 0xcf, 0xbe, 0xaf, 0x31, 0xb7, 0xdc, 0x75, 0xea, 0x97, 0xe4, 0x18, 0x3a, 0x6e, 0xc0,
	0xfc, 0x90, 0x2b, 0x27, 0xe6, 0x64, 0x6b, 0xac, 0x27, 0x30, 0xbe, 0x97, 0x0a, 0x17, 0x0a, 0xe0,
	0x14, 0x40, 0x3a, 0x85, 0x81, 0xd4, 0x53, 0xad, 0x7f, 0x44, 0x23, 0x7b, 0x19, 0xc7, 0x34, 0x62,
	0x21, 0x16, 0xe3, 0x56, 0x35, 0x3d, 0x83, 0x55, 0x8d, 0x4b, 0xda, 0x6e, 0x9c, 0x51, 0x4f, 0xb4,
	0x55, 0x4b, 0x94, 0x9e, 0x82, 0xa9, 0x99, 0xac, 0x89, 0x19, 0x75, 0x31, 0x32, 0x80, 0x36, 0x7e,
	0x24, 0x8a, 0xa0, 0xed, 0xc8, 0xe3, 0xe4, 0xd3, 0x00, 0x53, 0xea, 0xdf, 0xe5, 0xe3, 0x92, 0x4b,
	0xb0, 0xe4, 0x06, 0x6e, 0x4b, 0xeb, 0x0b, 0x69, 0x68, 0x9f, 0xc1, 0xde, 0x6c, 0x6a, 0x25, 0xc1,
	0x9c, 0x2e, 0x91, 0x07, 0xb0, 0xb4, 0x85, 0x20, 0x19, 0xd5, 0xa1, 0x8d, 0xbb, 0xb5, 0xf7, 0xfe,
	0x06, 0xe5, 0xcc, 0x37, 0x60, 0x5d, 0xa1, 0xa8, 0x12, 0x23, 0x3b, 0x3f, 0x1f, 0xe9, 0x6b, 0xb1,
	0xb7, 0x7f, 0xed, 0x2b, 0xbe, 0xc7, 0x8e, 0xfa, 0xf5, 0x27, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x55, 0x45, 0x81, 0x96, 0x03, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	HashPassword(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashReply, error)
	Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationReply, error)
	GetAuthToken(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*AuthTokenReply, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) HashPassword(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashReply, error) {
	out := new(HashReply)
	err := c.cc.Invoke(ctx, "/auth_service.AuthService/HashPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationReply, error) {
	out := new(AuthenticationReply)
	err := c.cc.Invoke(ctx, "/auth_service.AuthService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAuthToken(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*AuthTokenReply, error) {
	out := new(AuthTokenReply)
	err := c.cc.Invoke(ctx, "/auth_service.AuthService/GetAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	HashPassword(context.Context, *HashRequest) (*HashReply, error)
	Authenticate(context.Context, *AuthenticationRequest) (*AuthenticationReply, error)
	GetAuthToken(context.Context, *AuthTokenRequest) (*AuthTokenReply, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) HashPassword(ctx context.Context, req *HashRequest) (*HashReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HashPassword not implemented")
}
func (*UnimplementedAuthServiceServer) Authenticate(ctx context.Context, req *AuthenticationRequest) (*AuthenticationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAuthServiceServer) GetAuthToken(ctx context.Context, req *AuthTokenRequest) (*AuthTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_HashPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HashPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.AuthService/HashPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HashPassword(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.AuthService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Authenticate(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.AuthService/GetAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAuthToken(ctx, req.(*AuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HashPassword",
			Handler:    _AuthService_HashPassword_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AuthService_Authenticate_Handler,
		},
		{
			MethodName: "GetAuthToken",
			Handler:    _AuthService_GetAuthToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
