// Code generated by protoc-gen-go. DO NOT EDIT.
// source: place.proto

package place_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlaceType int32

const (
	PlaceType_PLACE_TYPE_UNSPECIFIED    PlaceType = 0
	PlaceType_PLACE_TYPE_CLOTHING_STORE PlaceType = 1
	PlaceType_PLACE_TYPE_BEAUTY_STORE   PlaceType = 2
)

var PlaceType_name = map[int32]string{
	0: "PLACE_TYPE_UNSPECIFIED",
	1: "PLACE_TYPE_CLOTHING_STORE",
	2: "PLACE_TYPE_BEAUTY_STORE",
}

var PlaceType_value = map[string]int32{
	"PLACE_TYPE_UNSPECIFIED":    0,
	"PLACE_TYPE_CLOTHING_STORE": 1,
	"PLACE_TYPE_BEAUTY_STORE":   2,
}

func (x PlaceType) String() string {
	return proto.EnumName(PlaceType_name, int32(x))
}

func (PlaceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{0}
}

type PlaceRequest struct {
	Coordinates          *Coordinates `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Types                []PlaceType  `protobuf:"varint,2,rep,packed,name=types,proto3,enum=place_service.PlaceType" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlaceRequest) Reset()         { *m = PlaceRequest{} }
func (m *PlaceRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceRequest) ProtoMessage()    {}
func (*PlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{0}
}

func (m *PlaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceRequest.Unmarshal(m, b)
}
func (m *PlaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceRequest.Marshal(b, m, deterministic)
}
func (m *PlaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceRequest.Merge(m, src)
}
func (m *PlaceRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceRequest.Size(m)
}
func (m *PlaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceRequest proto.InternalMessageInfo

func (m *PlaceRequest) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *PlaceRequest) GetTypes() []PlaceType {
	if m != nil {
		return m.Types
	}
	return nil
}

type PlaceResponse struct {
	Places               []*Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceResponse) Reset()         { *m = PlaceResponse{} }
func (m *PlaceResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceResponse) ProtoMessage()    {}
func (*PlaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{1}
}

func (m *PlaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceResponse.Unmarshal(m, b)
}
func (m *PlaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceResponse.Marshal(b, m, deterministic)
}
func (m *PlaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceResponse.Merge(m, src)
}
func (m *PlaceResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceResponse.Size(m)
}
func (m *PlaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceResponse proto.InternalMessageInfo

func (m *PlaceResponse) GetPlaces() []*Place {
	if m != nil {
		return m.Places
	}
	return nil
}

func (m *PlaceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Place struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates          *Coordinates `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Type                 PlaceType    `protobuf:"varint,4,opt,name=type,proto3,enum=place_service.PlaceType" json:"type,omitempty"`
	Distance             *Distance    `protobuf:"bytes,5,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration             *Duration    `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{2}
}

func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Place) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Place) GetType() PlaceType {
	if m != nil {
		return m.Type
	}
	return PlaceType_PLACE_TYPE_UNSPECIFIED
}

func (m *Place) GetDistance() *Distance {
	if m != nil {
		return m.Distance
	}
	return nil
}

func (m *Place) GetDuration() *Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type Coordinates struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{3}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Coordinates) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Distance struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Distance) Reset()         { *m = Distance{} }
func (m *Distance) String() string { return proto.CompactTextString(m) }
func (*Distance) ProtoMessage()    {}
func (*Distance) Descriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{4}
}

func (m *Distance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distance.Unmarshal(m, b)
}
func (m *Distance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distance.Marshal(b, m, deterministic)
}
func (m *Distance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distance.Merge(m, src)
}
func (m *Distance) XXX_Size() int {
	return xxx_messageInfo_Distance.Size(m)
}
func (m *Distance) XXX_DiscardUnknown() {
	xxx_messageInfo_Distance.DiscardUnknown(m)
}

var xxx_messageInfo_Distance proto.InternalMessageInfo

func (m *Distance) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Distance) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Duration struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_24becf27bd38ec36, []int{5}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Duration) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("place_service.PlaceType", PlaceType_name, PlaceType_value)
	proto.RegisterType((*PlaceRequest)(nil), "place_service.PlaceRequest")
	proto.RegisterType((*PlaceResponse)(nil), "place_service.PlaceResponse")
	proto.RegisterType((*Place)(nil), "place_service.Place")
	proto.RegisterType((*Coordinates)(nil), "place_service.Coordinates")
	proto.RegisterType((*Distance)(nil), "place_service.Distance")
	proto.RegisterType((*Duration)(nil), "place_service.Duration")
}

func init() { proto.RegisterFile("place.proto", fileDescriptor_24becf27bd38ec36) }

var fileDescriptor_24becf27bd38ec36 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xbe, 0xb4, 0x4d, 0xbd, 0x4e, 0x3c, 0x2d, 0xcb, 0xe1, 0xad, 0x3d, 0x85, 0x92, 0xa7, 0x22,
	0x47, 0xc1, 0x9e, 0x8f, 0xbe, 0x9c, 0xbd, 0xa8, 0x85, 0xa3, 0x17, 0xb6, 0x39, 0xe4, 0x5e, 0x0c,
	0x7b, 0xc9, 0x10, 0x02, 0xbd, 0x24, 0x66, 0xb7, 0xc5, 0x82, 0xff, 0xc0, 0x3f, 0x2d, 0xbb, 0xd9,
	0xd4, 0x58, 0x82, 0xe8, 0xdb, 0xcc, 0x7c, 0xdf, 0x97, 0x2f, 0xf3, 0x31, 0x0b, 0x4e, 0xb1, 0xe6,
	0x11, 0x4e, 0x8b, 0x32, 0x97, 0x39, 0x39, 0xd1, 0x4d, 0x28, 0xb0, 0xdc, 0xa6, 0x11, 0xba, 0x3f,
	0xe0, 0xa9, 0xaf, 0x06, 0x0c, 0xbf, 0x6d, 0x50, 0x48, 0xf2, 0x1e, 0x9c, 0x28, 0xcf, 0xcb, 0x38,
	0xcd, 0xb8, 0x44, 0x41, 0xad, 0xb1, 0x35, 0x71, 0x66, 0xa3, 0xe9, 0x1f, 0xa2, 0xe9, 0xfc, 0x37,
	0x83, 0x35, 0xe9, 0x64, 0x0a, 0xb6, 0xdc, 0x15, 0x28, 0x68, 0x67, 0xdc, 0x9d, 0x3c, 0x9b, 0xd1,
	0x03, 0x9d, 0x76, 0x0a, 0x76, 0x05, 0xb2, 0x8a, 0xe6, 0x7e, 0x81, 0x13, 0xe3, 0x2e, 0x8a, 0x3c,
	0x13, 0x48, 0x2e, 0xa0, 0xaf, 0x25, 0xca, 0xb9, 0x3b, 0x71, 0x66, 0xa7, 0x6d, 0x5f, 0x60, 0x86,
	0x43, 0x28, 0x3c, 0x79, 0x44, 0x21, 0x78, 0x82, 0xb4, 0x33, 0xb6, 0x26, 0x03, 0x56, 0xb7, 0xee,
	0xcf, 0x0e, 0xd8, 0x9a, 0x4b, 0x08, 0xf4, 0x32, 0xfe, 0x88, 0x7a, 0x93, 0x01, 0xd3, 0xb5, 0xd2,
	0xf1, 0x38, 0x2e, 0x51, 0x88, 0x5a, 0x67, 0xda, 0xc3, 0xf5, 0xbb, 0xff, 0xb7, 0xfe, 0x05, 0xf4,
	0xd4, 0x5e, 0xb4, 0x37, 0xb6, 0xfe, 0xba, 0xbd, 0x66, 0x91, 0x4b, 0x38, 0x8e, 0x53, 0x21, 0x79,
	0x16, 0x21, 0xb5, 0xb5, 0xd1, 0xd9, 0x81, 0xe2, 0xda, 0xc0, 0x6c, 0x4f, 0xd4, 0xa2, 0x4d, 0xc9,
	0x65, 0x9a, 0x67, 0xb4, 0xdf, 0x2e, 0x32, 0x30, 0xdb, 0x13, 0xdd, 0xb7, 0xe0, 0x34, 0xfe, 0x99,
	0x0c, 0xa1, 0xbb, 0xe6, 0x52, 0x27, 0x62, 0x31, 0x55, 0xea, 0x49, 0x96, 0xe8, 0x30, 0xd4, 0x24,
	0x4b, 0xdc, 0x77, 0x70, 0x5c, 0xbb, 0xab, 0x08, 0x25, 0x7e, 0x97, 0x75, 0x84, 0xaa, 0x26, 0xa7,
	0x60, 0x6f, 0xf9, 0x7a, 0x53, 0x05, 0x6f, 0xb3, 0xaa, 0xd1, 0x2a, 0x63, 0xfa, 0xef, 0xaa, 0x37,
	0x11, 0x0c, 0xf6, 0xd9, 0x90, 0x11, 0xbc, 0xf0, 0x6f, 0xae, 0xe6, 0x5e, 0x18, 0xdc, 0xfb, 0x5e,
	0x78, 0xb7, 0x5c, 0xf9, 0xde, 0x7c, 0xf1, 0x71, 0xe1, 0x5d, 0x0f, 0x8f, 0xc8, 0x6b, 0x78, 0xd9,
	0xc0, 0xe6, 0x37, 0xb7, 0xc1, 0xe7, 0xc5, 0xf2, 0x53, 0xb8, 0x0a, 0x6e, 0x99, 0x37, 0xb4, 0xc8,
	0x39, 0x9c, 0x35, 0xe0, 0x0f, 0xde, 0xd5, 0x5d, 0x70, 0x6f, 0xc0, 0xce, 0xec, 0xab, 0x39, 0xf4,
	0x55, 0x15, 0x13, 0x59, 0xc2, 0xf3, 0x04, 0xe5, 0x12, 0x79, 0xf9, 0xb0, 0xf3, 0xab, 0x73, 0x3a,
	0x6f, 0x3d, 0xb6, 0xea, 0x61, 0x8c, 0x5e, 0xb5, 0x83, 0xd5, 0xdd, 0xba, 0x47, 0x0f, 0x7d, 0xfd,
	0xbc, 0x2e, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x23, 0xec, 0xcd, 0xa3, 0x6d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaceServiceClient is the client API for PlaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceServiceClient interface {
	GetNearbyPlaces(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*PlaceResponse, error)
}

type placeServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlaceServiceClient(cc *grpc.ClientConn) PlaceServiceClient {
	return &placeServiceClient{cc}
}

func (c *placeServiceClient) GetNearbyPlaces(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*PlaceResponse, error) {
	out := new(PlaceResponse)
	err := c.cc.Invoke(ctx, "/place_service.PlaceService/getNearbyPlaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceServiceServer is the server API for PlaceService service.
type PlaceServiceServer interface {
	GetNearbyPlaces(context.Context, *PlaceRequest) (*PlaceResponse, error)
}

// UnimplementedPlaceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlaceServiceServer struct {
}

func (*UnimplementedPlaceServiceServer) GetNearbyPlaces(ctx context.Context, req *PlaceRequest) (*PlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearbyPlaces not implemented")
}

func RegisterPlaceServiceServer(s *grpc.Server, srv PlaceServiceServer) {
	s.RegisterService(&_PlaceService_serviceDesc, srv)
}

func _PlaceService_GetNearbyPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).GetNearbyPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place_service.PlaceService/GetNearbyPlaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).GetNearbyPlaces(ctx, req.(*PlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "place_service.PlaceService",
	HandlerType: (*PlaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNearbyPlaces",
			Handler:    _PlaceService_GetNearbyPlaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "place.proto",
}
